language: ruby
script:
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
  - .forge-releng/publish
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
env:
  global:
    - PUBLISHER_LOGIN=jhoblitt
    - secure: "bBjR8uB4T5mJpB1wYepqqgDO9R82IA8AKT3d5GNSY021xOZLv59bJfYMAxnD2lF4SKpUX+SYR/JeMs5RYkHes0QB8gat0Ast+uaDteEwQb1clksHmEteRFqEZfcQs/M7XuB5gOUxbSP6VZdPSiRcQzm6wHaUvFBzGr/c79g5fR8="
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.0.0"
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.1"
    - PUPPET_GEM_VERSION="~> 3.3.0"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 3.2.1"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 3.3.0"
notifications:
  email: false
